<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="OneOf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoTest.Domain\AutoTest.Domain.csproj" />
    <ProjectReference Include="..\AutoTest.Persistence\AutoTest.Persistence.csproj" />
  </ItemGroup>

</Project>
