import { resolve } from "path";
import envVars from "preact-cli-plugin-env-vars";

export default {
  webpack(config, env, helpers) {
    config.module.rules[4].use.splice(1, 0, {
      loader: "@teamsupercell/typings-for-css-modules-loader",
      options: {
        banner:
          "// This file is automatically generated from your CSS. Any edits will be overwritten.",
        disableLocalsExport: true,
      },
    });

    config.resolve.alias["preact-cli-entrypoint"] = resolve(
      process.cwd(),
      "src",
      "index",
    );

    const critters = helpers.getPluginsByName(config, "Critters")[0];
    if (critters) {
      config.plugins.splice(critters.index, 1);
    }

    envVars(config, env, helpers);
  },
};
