name: .NET Core

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "AutoTest.Web/ClientApp/**"
      - "**/*.md"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "AutoTest.Web/ClientApp/**"
      - "**/*.md"

concurrency:
  group: dotnet-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./AutoTest.Web --configuration Release --no-restore
    - name: Test Unit
      run: dotnet test ./Test/AutoTest.Unit.Test --configuration Release --no-restore
    - name: Test Integration
      run: dotnet test ./Test/AutoTest.Integration.Test --configuration Release --no-restore
